
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshop
    username: postgres
    password: postgres1105

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8081



